complianceRequirements:
  medicalLicenseVerification:
    description: Verify valid medical license for surgeons.
    verificationMethod: externalAPI
    apiEndpoint: https://api.medicalboard.gov/verify
    requiredFields:
      - licenseNumber
      - issuingState
  surgicalCertificationVerification:
    description: Confirm surgical specialty certifications.
    verificationMethod: externalAPI
    apiEndpoint: https://api.surgicalboard.gov/verify
    requiredFields:
      - certificationNumber
      - specialty
  hipaaCompliance:
    description: Ensure patient data is handled per HIPAA regulations.
    regulations:
      - HIPAA Privacy Rule
      - HIPAA Security Rule
    enforcementActions:
      - dataEncryption: true
      - accessLogging: true
